export const PLUGIN_ID = "bases-improvements";

export const SETTINGS_DEFAULTS = {
	DEFAULT_CODE_FENCE_LANGUAGE: "base",
	DEFAULT_TARGET_EMBEDS: true,

	DEFAULT_INPUT_DEBOUNCE_MS: 250,
	DEFAULT_UPDATE_DEBOUNCE_MS: 250,
} as const;
